tenant: jira-difli
namespace: default
name: vectorize-function
# Update to the absolute path of the function's package
py: /Users/dieter.flick/Documents/development/workspaces/workspace-jira/demo/pulsar-functions/vectorize-function/vectorize.zip
# className convention: filename.classname
className: vectorize.VectorizeFunction
parallelism: 1
inputs:
 - persistent://jira-difli/default/jira-stream
output: persistent://jira-difli/default/jira-stream-vectorized
autoAck: true
logTopic: persistent://jira-difli/default/jira-stream-log
userConfig:
 logging_level: ERROR